Give yield_module what it expects
Otherwise I get

  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'tuple'

When I rerun sphinx-build